[project]
name = "liber-usualis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bottle>=0.13.4",
    "diff-match-patch>=20241021",
    "pytest>=9.0.2",
    "requests>=2.32.5",
    "waitress>=3.0.2",
    "wsgi-request-logger>=0.4.6",
]

[tool.setuptools]
packages = ["web", "data", "kalendar"]
