# Copyright 2026 (AGPL-3.0-or-later), Miles K. Bertrand et al.

# All code in this module was generated by Claude Sonnet 5 as a 1-1 port of human written Javascript original code.

from renderer.rite_renderer import render_rite

__all__ = ['render_rite']
