# Copyright 2026 (AGPL-3.0-or-later), Miles K. Bertrand et al.

# All code in this module was generated by Claude Sonnet 5 as a 1-1 port of human written Javascript original code.

import re
from typing import Any, Union

MONTHS = ['Januarii', 'Februarii', 'Martii', 'Aprilis', 'Maji', 'Junii', 'Julii', 'Augusti', 'Septembris', 'Octobris', 'Novembris', 'Decembris']

def date_header(date: str) -> str:
    year, month, day = date.split('-')
    return f'<h4 class="date-header">Die {int(day)} {MONTHS[(int(month) - 1) % 12]} {year}.</h4>'

def rite_title(title: str, tagset: frozenset[str], size: str = 'large') -> str:
    if size == 'small':
        return f'<h1 class="small-title">{title}</h1>'

    if 'duplex-i-classis' in tagset:
        subtitle = 'Duplex I. Classis.'
    elif 'duplex-ii-classis' in tagset:
        subtitle = 'Duplex II. Classis.'
    elif 'duplex-majus' in tagset:
        subtitle = 'Duplex Majus.'
    elif 'duplex-minus' in tagset:
        subtitle = 'Duplex Minus.'
    elif 'semiduplex' in tagset:
        subtitle = 'Semiduplex.'
    elif 'simplex' in tagset or 'feria' in tagset:
        subtitle = 'Simplex.'
    else:
        subtitle = ''

    if 'mtv' in tagset:
        subtitle += ' (m.t.v.)'

    title_text = re.sub(r'\.\.$', '.', title + '.')
    return f'<h1 class="large-title">{title_text}</h1><h2 class="large-subtitle">{subtitle}</h2>'

_ABBREVIATIONS = (
    ('Martyris', 'Mart.'),
    ('Martyrum', 'Mm.'),
    ('Confessoris', 'Conf.'),
    ('Episcopi', 'Ep.'),
    ('Pontificum', 'Pont.'),
    ('Ecclesiæ Doctoris', 'Eccl. Doct.'),
    ('Virginis', 'Virg.'),
    ('Viduæ', 'Vid.'),
    ('Sociorum', 'Soc.'),
)

def abbreviate_name(name: str) -> str:
    for full, short in _ABBREVIATIONS:
        name = name.replace(full, short)
    name = name + '.'
    name = re.sub(r'\.\.$', '.', name)
    return name

_ACCENT_FLATTEN = (('Á', 'A'), ('Ǽ', 'Æ'), ('É', 'E'), ('Í', 'I'), ('Ó', 'O'), ('Ú', 'U'), ('Ý', 'Y'))

def _flatten_uppercase_accents(text: str) -> str:
    for accented, plain in _ACCENT_FLATTEN:
        text = text.replace(accented, plain)
    return text

def rubric_render(data: str) -> str:
    data = re.sub(r'\[(.+?)\]', r"<span class='black-rubric'>\1</span>", data)
    data = _flatten_uppercase_accents(data)
    data = re.sub(r'(?<!<)/', '<br>', data)
    data = re.sub(r'\n', '<br>', data)
    data = re.sub(r'&para;', "<span class='red'>&para;</span>", data)
    data = re.sub(r'N\.', "<span class='red'>N.</span>", data)
    # Trailing "." here is an unescaped regex wildcard in the JS original
    # (matches "R. br" + any one character), not a literal period -- kept
    # as-is for faithful parity rather than "fixed".
    data = re.sub(r'R\. br.', "<span class='red'>&#8479;. br.</span>", data)
    data = re.sub(r'R\.', "<span class='red'>&#8479;.</span>", data)
    data = re.sub(r'^V\.', "<span class='red'>&#8483;.</span>", data)
    data = re.sub(r'>V\.', "<br><span class='red'>&#8483;.</span>", data)
    data = data.replace('✠', "<span class='red'>&malt;</span>")
    data = data.replace('✙', "<span class='red'>&#10009;</span>")
    data = data.replace('+', "<span class='red'>&dagger;</span>")
    data = data.replace('*', "<span class='red'>&ast;</span>")
    return data

def string_render(text: str) -> str:
    if re.fullmatch(r'\[.+?\]', text):
        return f"<span class='rite-text-rubric'>{rubric_render(text[1:-1])}</span>"

    text = _flatten_uppercase_accents(text)
    text = re.sub(r'(?<!<)/', '<br>', text)
    text = re.sub(r'([0-9]+)\s', r'<span class="verse-number">\1 </span>', text)
    text = re.sub(r'\n', '<br>', text)
    text = re.sub(r'^V\.', '<span class="red line-starting-symbol">&#8483;.</span>', text)
    # See rubric_render: trailing "." is an unescaped wildcard, kept for parity.
    text = re.sub(r'^R\. br.', '<span class="red line-starting-symbol">&#8479;. br.</span>', text)
    text = re.sub(r'^R\.', '<span class="red line-starting-symbol">&#8479;.</span>', text)
    text = re.sub(r'&para;', "<span class='red'>&para;</span>", text)
    text = re.sub(r'N\.', "<span class='red'>N.</span>", text)
    text = re.sub(r'R\.', "<span class='red'>&#8479;.</span>", text)
    text = re.sub(r'<br>V\.', "<br><span class='red'>&#8483;.</span>", text)
    text = text.replace('✠', "<span class='red'>&malt;</span>")
    text = text.replace('✙', "<span class='red'>&#10009;</span>")
    text = text.replace('+', "<span class='red'>&dagger;</span>")
    text = text.replace('*', "<span class='red'>&ast;</span>")
    text = re.sub(r'\[\((.+?)\)\]\s', r"<span class='rite-text-rubric small-rubric'>(\1) </span>", text)
    text = re.sub(r'\[(.+?)\]', r"<span class='rite-text-rubric'>\1</span>", text)
    return text

# It can be readily observed that this is just an extremely primitive version of render_rite().
def unpack(data: Union[str, list, dict, None]) -> Union[str, list, None]:
    if isinstance(data, str):
        return data
    if data is None:
        return None
    if isinstance(data, list):
        result: list[Any] = []
        for item in data:
            unpacked = unpack(item)
            if isinstance(unpacked, list):
                result.extend(unpacked)
            else:
                result.append(unpacked)
        return result
    if isinstance(data, dict):
        return unpack(data.get('datum'))
    return None

# Digs out nested data recursively (useful for translation).
def claw(data: dict) -> dict:
    datum = data.get('datum')
    if isinstance(datum, str) or isinstance(datum, list):
        return data
    return claw(datum)
